In [5]:
import pandas as pd
sur2 = pd.read_csv("/Users/yuuki/Raw.csv")

In [7]:
yuru = sur2[(sur2["q2c2"]==1) | (sur2["q2c3"]==1) | (sur2["q2c4"]==1) | (sur2["q2c5"]==1) | (sur2["q2c7"]==1) | (sur2["q2c8"]==1) | (sur2["q2c9"]==1) | (sur2["q2c10"]==1)]


In [8]:
yuru.describe()

SEX         AGE         GEN         PRE         ARE         JOB  \
count  237.000000  237.000000  237.000000  237.000000  237.000000  237.000000   
mean     1.518987   49.236287    5.514768   20.004219    4.088608    6.324895   
std      0.500697    5.649647    0.500840   10.512905    1.593338    2.802831   
min      1.000000   40.000000    5.000000    1.000000    1.000000    1.000000   
25%      1.000000   44.000000    5.000000   13.000000    3.000000    4.000000   
50%      2.000000   50.000000    6.000000   19.000000    4.000000    6.000000   
75%      2.000000   54.000000    6.000000   27.000000    5.000000    9.000000   
max      2.000000   59.000000    6.000000   47.000000    8.000000   11.000000   

              MAR         CHI        q1s1        q1s2  ...        q5s7  \
count  237.000000  237.000000  237.000000  237.000000  ...  237.000000   
mean     1.658228    1.396624    1.586498    2.464135  ...    2.489451   
std      0.475307    0.490232    0.608822    0.673170  ...    1.048048   
min      1.000000    1.000000    1.000000    1.000000  ...    1.000000   
25%      1.000000    1.000000    1.000000    2.000000  ...    2.000000   
50%      2.000000    1.000000    2.000000    3.000000  ...    2.000000   
75%      2.000000    2.000000    2.000000    3.000000  ...    3.000000   
max      2.000000    2.000000    3.000000    3.000000  ...    5.000000   

             q5s8        q5s9       q5s10       q5s11       q5s12       q5s13  \
count  237.000000  237.000000  237.000000  237.000000  237.000000  237.000000   
mean     2.493671    2.835443    2.210970    2.970464    2.333333    2.540084   
std      1.023538    1.078649    0.946563    1.086889    0.984341    1.047332   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      2.000000    2.000000    2.000000    2.000000    2.000000    2.000000   
50%      3.000000    3.000000    2.000000    3.000000    2.000000    3.000000   
75%      3.000000    3.000000    3.000000    4.000000    3.000000    3.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

            q5s14       q5s15          q6  
count  237.000000  237.000000  237.000000  
mean     2.556962    2.265823    2.725738  
std      0.983941    1.025632    1.114566  
min      1.000000    1.000000    1.000000  
25%      2.000000    1.000000    2.000000  
50%      3.000000    2.000000    3.000000  
75%      3.000000    3.000000    3.000000  
max      5.000000    5.000000    5.000000  

[8 rows x 46 columns]

In [9]:
yuru = yuru[(yuru["q3"]==4) | (yuru["q3"]==5)]

In [10]:
yuru = yuru[(yuru["q4"]==5) | (yuru["q4"]==6)]
yuru.describe()

SEX        AGE        GEN        PRE        ARE        JOB  \
count  22.000000  22.000000  22.000000  22.000000  22.000000  22.000000   
mean    1.590909  51.227273   5.636364  21.909091   4.318182   5.772727   
std     0.503236   5.614029   0.492366   8.029168   1.170525   3.191235   
min     1.000000  42.000000   5.000000   5.000000   2.000000   1.000000   
25%     1.000000  46.500000   5.000000  14.000000   3.000000   3.000000   
50%     2.000000  50.500000   6.000000  24.500000   5.000000   4.000000   
75%     2.000000  56.750000   6.000000  27.000000   5.000000   9.000000   
max     2.000000  59.000000   6.000000  34.000000   6.000000  11.000000   

             MAR        CHI       q1s1       q1s2  ...       q5s7       q5s8  \
count  22.000000  22.000000  22.000000  22.000000  ...  22.000000  22.000000   
mean    1.681818   1.363636   2.000000   2.818182  ...   3.090909   3.181818   
std     0.476731   0.492366   0.534522   0.394771  ...   1.019294   0.906924   
min     1.000000   1.000000   1.000000   2.000000  ...   2.000000   2.000000   
25%     1.000000   1.000000   2.000000   3.000000  ...   2.000000   3.000000   
50%     2.000000   1.000000   2.000000   3.000000  ...   3.000000   3.000000   
75%     2.000000   2.000000   2.000000   3.000000  ...   4.000000   4.000000   
max     2.000000   2.000000   3.000000   3.000000  ...   5.000000   5.000000   

            q5s9      q5s10      q5s11      q5s12      q5s13      q5s14  \
count  22.000000  22.000000  22.000000  22.000000  22.000000  22.000000   
mean    3.454545   2.363636   3.409091   2.727273   3.227273   3.181818   
std     1.010765   0.847711   0.908116   1.077113   0.922307   0.906924   
min     2.000000   1.000000   2.000000   1.000000   2.000000   2.000000   
25%     3.000000   2.000000   3.000000   2.000000   3.000000   3.000000   
50%     3.000000   2.000000   3.000000   3.000000   3.000000   3.000000   
75%     4.000000   3.000000   4.000000   3.000000   4.000000   4.000000   
max     5.000000   5.000000   5.000000   5.000000   5.000000   5.000000   

           q5s15         q6  
count  22.000000  22.000000  
mean    2.863636   2.681818  
std     0.833550   1.086119  
min     1.000000   1.000000  
25%     2.000000   2.000000  
50%     3.000000   3.000000  
75%     3.000000   3.000000  
max     4.000000   5.000000  

[8 rows x 46 columns]

In [11]:
yuru["q4"].describe()

count    22.000000
mean      5.727273
std       0.455842
min       5.000000
25%       5.250000
50%       6.000000
75%       6.000000
max       6.000000
Name: q4, dtype: float64

In [12]:
yuru["q3"].describe()

count    22.000000
mean      4.318182
std       0.476731
min       4.000000
25%       4.000000
50%       4.000000
75%       5.000000
max       5.000000
Name: q3, dtype: float64

In [18]:
yuru = yuru.reset_index(drop = True)

In [19]:
gati = sur2[(sur2["q2c1"]==1) | (sur2["q2c6"]==1)]

In [20]:
gati = gati[(gati["q2c2"]==0) & (gati["q2c3"]==0) & (gati["q2c4"]==0) & (gati["q2c5"]==0) & (gati["q2c7"]==0) & (gati["q2c8"]==0) & (gati["q2c9"]==0) & (gati["q2c10"]==0) ]

In [21]:
gati = gati[(gati["q3"]==1) | (gati["q3"]==2) | (gati["q3"]==3)]

In [22]:
gati = gati[(gati["q4"]==1) | (gati["q4"]==2) | (gati["q4"]==3) | (gati["q4"]==4)]

In [23]:
gati.describe()

SEX       AGE       GEN        PRE       ARE        JOB       MAR  \
count  8.00000   8.00000  8.000000   8.000000  8.000000   8.000000  8.000000   
mean   1.25000  49.00000  5.500000  12.750000  3.125000   5.250000  1.625000   
std    0.46291   6.78233  0.534522   5.800246  0.834523   3.575712  0.517549   
min    1.00000  40.00000  5.000000   5.000000  2.000000   1.000000  1.000000   
25%    1.00000  43.00000  5.000000   9.000000  2.750000   2.500000  1.000000   
50%    1.00000  49.00000  5.500000  12.500000  3.000000   5.500000  2.000000   
75%    1.25000  54.00000  6.000000  17.000000  4.000000   6.750000  2.000000   
max    2.00000  58.00000  6.000000  22.000000  4.000000  11.000000  2.000000   

            CHI      q1s1      q1s2  ...     q5s7      q5s8      q5s9  \
count  8.000000  8.000000  8.000000  ...  8.00000  8.000000  8.000000   
mean   1.375000  1.375000  2.125000  ...  2.12500  2.500000  2.625000   
std    0.517549  0.517549  0.834523  ...  0.64087  1.195229  0.916125   
min    1.000000  1.000000  1.000000  ...  1.00000  1.000000  2.000000   
25%    1.000000  1.000000  1.750000  ...  2.00000  2.000000  2.000000   
50%    1.000000  1.000000  2.000000  ...  2.00000  2.000000  2.000000   
75%    2.000000  2.000000  3.000000  ...  2.25000  3.000000  3.250000   
max    2.000000  2.000000  3.000000  ...  3.00000  5.000000  4.000000   

         q5s10     q5s11     q5s12     q5s13    q5s14     q5s15        q6  
count  8.00000  8.000000  8.000000  8.000000  8.00000  8.000000  8.000000  
mean   2.12500  2.375000  2.625000  2.250000  2.25000  2.250000  2.375000  
std    0.64087  0.744024  0.744024  0.707107  0.46291  0.707107  1.407886  
min    1.00000  1.000000  1.000000  1.000000  2.00000  1.000000  1.000000  
25%    2.00000  2.000000  2.750000  2.000000  2.00000  2.000000  1.750000  
50%    2.00000  2.500000  3.000000  2.000000  2.00000  2.000000  2.000000  
75%    2.25000  3.000000  3.000000  3.000000  2.25000  3.000000  2.500000  
max    3.00000  3.000000  3.000000  3.000000  3.00000  3.000000  5.000000  

[8 rows x 46 columns]

In [56]:
# スコアを変換する
# ”ゆる”とそれ以外
# 質より料金が大事
import numpy as np
cnt_q5s11 = [0,0,0,0,0]
for i in range(len(yuru)):
    tmp = yuru["q5s11"][i]
    tmp -= 1
    cnt_q5s11[tmp] += 1
cnt_q5s11 = np.array(cnt_q5s11)
cnt_q5s11

array([ 0,  3, 10,  6,  3])

In [57]:
score = np.array([5,4,3,2,1])
ans = sum(cnt_q5s11*score)
ans /= 22
print("ゆる層で、質より料金：　" + str(ans))
answer = []
answer.append(ans)

ゆる層で、質より料金：　2.590909090909091


In [58]:
Allcnt_q5s11 = [0,0,0,0,0]
for i in range(len(sur2)):
    tmp = sur2["q5s11"][i]
    tmp -= 1
    Allcnt_q5s11[tmp] += 1
Allcnt_q5s11 = np.array(Allcnt_q5s11)

In [59]:
Sacnt_q5s11 = Allcnt_q5s11 - cnt_q5s11
Sacnt_q5s11

array([ 24,  60, 101,  37,  25])

In [60]:
ans = sum(Sacnt_q5s11*score)
ans /= sum(Sacnt_q5s11)
print(ans)
answer.append(ans)

3.08502024291498


In [61]:
print("ゆる層以外で、質より料金：　" + str(ans))

ゆる層以外で、質より料金：　3.08502024291498


In [62]:
# 好きな時間に学びたい
# q5s3
cnt_q5s3 = [0,0,0,0,0]
for i in range(len(yuru)):
    tmp = yuru["q5s3"][i]
    tmp -= 1
    cnt_q5s3[tmp] += 1
cnt_q5s3= np.array(cnt_q5s3)
cnt_q5s3

array([ 0, 17,  4,  1,  0])

In [64]:
ans = sum(cnt_q5s3*score)
ans /= 22
print("ゆる層で、好きな時間に学びたい：　" + str(ans))

ゆる層で、好きな時間に学びたい：　3.727272727272727


In [65]:
answer.append(ans)

In [66]:
answer

[2.590909090909091, 3.08502024291498, 3.727272727272727]

In [68]:
Allcnt_q5s3 = [0,0,0,0,0]
for i in range(len(sur2)):
    tmp = sur2["q5s3"][i]
    tmp -= 1
    Allcnt_q5s3[tmp] += 1
Allcnt_q5s3 = np.array(Allcnt_q5s3)
Sacnt_q5s3 = Allcnt_q5s3 - cnt_q5s3
print(Sacnt_q5s3)
ans = sum(Sacnt_q5s3*score)
ans /= sum(Sacnt_q5s3)
print(ans)


[ 82 105  46   9   5]
4.012145748987854


In [73]:
test = 82*5 + 105*4 + 46*3 + 9*2 + 5
test /= 247
print(test)

answer

4.012145748987854


[2.590909090909091, 3.08502024291498, 3.727272727272727, 4.012145748987854]

In [75]:
# 課題を与えられるよりも、自由に話したい
# q5s6
cnt_q5s6= [0,0,0,0,0]
for i in range(len(yuru)):
    tmp = yuru["q5s6"][i]
    tmp -= 1
    cnt_q5s6[tmp] += 1
cnt_q5s6= np.array(cnt_q5s6)
print(cnt_q5s6)
ans = sum(cnt_q5s6*score)
ans /= 22
print("ゆる層で、自由に話したい：　" + str(ans))

[ 1  5 14  1  1]
ゆる層で、自由に話したい：　3.1818181818181817


In [76]:
answer.append(ans)

In [77]:
Allcnt_q5s6 = [0,0,0,0,0]
for i in range(len(sur2)):
    tmp = sur2["q5s6"][i]
    tmp -= 1
    Allcnt_q5s6[tmp] += 1
Allcnt_q5s6 = np.array(Allcnt_q5s6)
Sacnt_q5s6 = Allcnt_q5s6 - cnt_q5s6
print(Sacnt_q5s6)
ans = sum(Sacnt_q5s6*score)
ans /= sum(Sacnt_q5s6)
print(ans)


[42 99 88 12  6]
3.6437246963562755


In [78]:
answer.append(ans)

In [79]:
# レベルに合わせて欲しい
# q5s10
cnt_q5s10= [0,0,0,0,0]
for i in range(len(yuru)):
    tmp = yuru["q5s10"][i]
    tmp -= 1
    cnt_q5s10[tmp] += 1
cnt_q5s10= np.array(cnt_q5s10)
print(cnt_q5s10)
ans = sum(cnt_q5s10*score)
ans /= 22
print(ans)

[ 2 12  7  0  1]
3.6363636363636362


In [80]:
answer.append(ans)

In [81]:
Allcnt_q5s10 = [0,0,0,0,0]
for i in range(len(sur2)):
    tmp = sur2["q5s10"][i]
    tmp -= 1
    Allcnt_q5s10[tmp] += 1
Allcnt_q5s10 = np.array(Allcnt_q5s10)
Sacnt_q5s10 = Allcnt_q5s10 - cnt_q5s10
print(Sacnt_q5s10)
ans = sum(Sacnt_q5s10*score)
ans /= sum(Sacnt_q5s10)
print(ans)


[ 57 100  75   8   7]
3.777327935222672


In [82]:
answer.append(ans)

In [87]:
# 趣味について語りたい
# q5s8
cnt_q5s8= [0,0,0,0,0]
for i in range(len(yuru)):
    tmp = yuru["q5s8"][i]
    tmp -= 1
    cnt_q5s8[tmp] += 1
cnt_q5s8= np.array(cnt_q5s8)
print(cnt_q5s8)
ans = sum(cnt_q5s8*score)
ans /= 22
print(ans)
answer.append(ans)

[ 0  5 10  5  2]
2.8181818181818183


In [88]:
Allcnt_q5s8 = [0,0,0,0,0]
for i in range(len(sur2)):
    tmp = sur2["q5s8"][i]
    tmp -= 1
    Allcnt_q5s8[tmp] += 1
Allcnt_q5s8 = np.array(Allcnt_q5s8)
Sacnt_q5s8 = Allcnt_q5s8 - cnt_q5s8
print(Sacnt_q5s8)
ans = sum(Sacnt_q5s8*score)
ans /= sum(Sacnt_q5s8)
print(ans)
answer.append(ans)

[44 83 87 24  9]
3.522267206477733


In [90]:
# 専門資格を持つ講師から学びたい
# q5s14
cnt_q5s14= [0,0,0,0,0]
for i in range(len(yuru)):
    tmp = yuru["q5s14"][i]
    tmp -= 1
    cnt_q5s14[tmp] += 1
cnt_q5s14= np.array(cnt_q5s14)
print(cnt_q5s14)
ans = sum(cnt_q5s14*score)
ans /= 22
print(ans)
answer.append(ans)

[ 0  5 10  5  2]
2.8181818181818183


In [92]:
Allcnt_q5s14 = [0,0,0,0,0]
for i in range(len(sur2)):
    tmp = sur2["q5s14"][i]
    tmp -= 1
    Allcnt_q5s14[tmp] += 1
Allcnt_q5s14 = np.array(Allcnt_q5s14)
Sacnt_q5s14 = Allcnt_q5s14 - cnt_q5s14
print(Sacnt_q5s14)
ans = sum(Sacnt_q5s14*score)
ans /= sum(Sacnt_q5s14)
print(ans)
answer.append(ans)

[36 82 99 22  8]
3.4696356275303644


In [93]:
labels = ["ゆる層で、質より料金が大事：　", "ゆる層以外で、質より料金が大事：　", "ゆる層で、好きな時間に学びたい：　", "ゆる層以外で、好きな時間に学びたい：　",
          "ゆる層で、自由に話したい：　","ゆる層以外で、自由に話したい：　","ゆる層で、レベルに合わせて欲しい：　","ゆる層以外で、レベルに合わせて欲しい：　",
          "ゆる層で、趣味について語りたい：　","ゆる層以外で、趣味について語りたい：　","ゆる層で、専門資格を持つ講師から学びたい：　","ゆる層以外で、専門資格を持つ講師から学びたい：　"]

In [94]:
for i in range(12):
    print(labels[i] + ": " + str(answer[i]) + "\n")

ゆる層で、質より料金が大事：　: 2.590909090909091

ゆる層以外で、質より料金が大事：　: 3.08502024291498

ゆる層で、好きな時間に学びたい：　: 3.727272727272727

ゆる層以外で、好きな時間に学びたい：　: 4.012145748987854

ゆる層で、自由に話したい：　: 3.1818181818181817

ゆる層以外で、自由に話したい：　: 3.6437246963562755

ゆる層で、レベルに合わせて欲しい：　: 3.6363636363636362

ゆる層以外で、レベルに合わせて欲しい：　: 3.777327935222672

ゆる層で、趣味について語りたい：　: 2.8181818181818183

ゆる層以外で、趣味について語りたい：　: 3.522267206477733

ゆる層で、専門資格を持つ講師から学びたい：　: 2.8181818181818183

ゆる層以外で、専門資格を持つ講師から学びたい：　: 3.4696356275303644



### 一応の結果は出たので、検定に入る
### ゆる層とそうでない層で、平均値に差があるかを検定する

In [97]:
import scipy 
import matplotlib.pyplot as plt
import statistics as stat

In [98]:
yuru2 = sur2[(sur2["q2c2"]==1) | (sur2["q2c3"]==1) | (sur2["q2c4"]==1) | (sur2["q2c5"]==1) | (sur2["q2c7"]==1) | (sur2["q2c8"]==1) | (sur2["q2c9"]==1) | (sur2["q2c10"]==1)]
yuru2 = yuru2[(yuru2["q3"]==4) | (yuru2["q3"]==5)]
yuru2 = yuru2[(yuru2["q4"]==5) | (yuru2["q4"]==6)]


In [100]:
drop_index = yuru2.index

In [101]:
drop_index

Int64Index([  6,  18,  29,  36,  45,  53,  54,  61,  64,  66,  71,  89, 141,
            160, 164, 178, 192, 201, 240, 242, 248, 254],
           dtype='int64')

In [102]:
len(drop_index)

22

In [103]:
notYuru = sur2.drop(drop_index)

In [104]:
notYuru

SEX  AGE  GEN  PRE  ARE  JOB  MAR  CHI  q1s1  q1s2  ...  q5s7  q5s8  \
0      2   58    6   13    3    8    2    1     2     3  ...     2     2   
1      2   55    6   14    3    9    2    1     2     3  ...     1     1   
2      1   57    6    4    2    6    2    2     1     3  ...     1     1   
3      2   56    6   23    4    9    2    1     1     3  ...     3     2   
4      2   58    6   14    3    9    2    2     1     1  ...     2     3   
..   ...  ...  ...  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...   
264    2   45    5   27    5    8    2    1     2     3  ...     3     3   
265    2   40    5   13    3    8    2    1     2     2  ...     1     1   
266    2   52    6   38    7    3    1    2     2     3  ...     2     2   
267    1   55    6   11    3    7    2    1     1     1  ...     1     3   
268    2   58    6   28    5    8    2    1     2     3  ...     2     2   

     q5s9  q5s10  q5s11  q5s12  q5s13  q5s14  q5s15  q6  
0       4      2      2      2      3      3      2   3  
1       4      1      3      2      3      3      1   1  
2       1      1      2      1      1      1      3   2  
3       3      3      3      3      3      3      2   2  
4       2      2      3      2      2      2      3   4  
..    ...    ...    ...    ...    ...    ...    ...  ..  
264     3      2      4      2      2      3      4   3  
265     1      1      3      1      1      1      1   1  
266     3      1      3      1      2      2      3   4  
267     3      1      2      2      2      1      2   3  
268     3      2      3      2      3      4      3   3  

[247 rows x 46 columns]

In [108]:
notYuru = notYuru.reset_index()
test = [0,0,0,0,0]
for i in range(247):
    tmp = notYuru["q5s11"][i]
    tmp -= 1
    test[tmp] += 1
test = np.array(test)
check = sum(test*score)
check /= 247
print(check)

3.08502024291498
